; PlatformIO Project Configuration File for Reva Car
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs =
description = Reva Robot Car Motor (M1 & M2) Control Project for Arduino Mega

[env:mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps = adafruit/Adafruit Motor Shield library @ ^1.0.1
upload_port = COM4


[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
